--Populating company table for TECHNOLOGY FIELD
INSERT INTO COMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_STANDING, COMPANY_COUNTRY, COMPANY_STATE, COMPANY_FIELD)
        VALUES(1, 'Apple', 'Corporate', 'United States', 'California', 'Technology');
INSERT INTO COMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_STANDING, COMPANY_COUNTRY, COMPANY_STATE, COMPANY_FIELD)
        VALUES(2, 'Amazon', 'Corporate', 'United States', 'Seattle', 'Technology');
INSERT INTO COMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_STANDING, COMPANY_COUNTRY, COMPANY_STATE, COMPANY_FIELD)
        VALUES(3, 'Meta', 'Corporate', 'United States', 'California', 'Technology');
INSERT INTO COMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_STANDING, COMPANY_COUNTRY, COMPANY_STATE, COMPANY_FIELD)
        VALUES(4, 'Netflix', 'Corporate', 'United States', 'California', 'Technology');
INSERT INTO COMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_STANDING, COMPANY_COUNTRY, COMPANY_STATE, COMPANY_FIELD)
        VALUES(5, 'Google', 'Corporate', 'United States', 'California', 'Technology');
INSERT INTO COMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_STANDING, COMPANY_COUNTRY, COMPANY_STATE, COMPANY_FIELD)
        VALUES(6, 'IBM', 'Corporate', 'United States', 'Georgia', 'Technology');
--Populating company table for HOSPITALITY FIELD
INSERT INTO COMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_COUNTRY, COMPANY_STATE, COMPANY_FIELD)
        VALUES(7, 'ABC Pizzas', 'Canada', 'Alberta', 'Hospitality');
INSERT INTO COMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_COUNTRY, COMPANY_STATE, COMPANY_FIELD)
        VALUES(8, 'Best Burgers', 'Canada', 'British Columbia', 'Hospitality');
INSERT INTO COMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_COUNTRY, COMPANY_STATE, COMPANY_FIELD)
        VALUES(9, 'Wicked Waffles', 'United States', 'Florida', 'Hospitality');
INSERT INTO COMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_COUNTRY, COMPANY_STATE, COMPANY_FIELD)
        VALUES(10, 'Sizzling Steak', 'United States', 'Alabama', 'Hospitality');
INSERT INTO COMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_COUNTRY, COMPANY_STATE, COMPANY_FIELD)
        VALUES(11, 'Nice Nachos', 'United States', 'Alabama', 'Hospitality');
INSERT INTO COMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_COUNTRY, COMPANY_STATE, COMPANY_FIELD)
        VALUES(12, 'Krispy Krabs', 'United States', 'Alabama', 'Hospitality');
--Populating company table for MEDICINE FIELD
INSERT INTO COMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_STANDING, COMPANY_COUNTRY, COMPANY_STATE, COMPANY_FIELD)
        VALUES(13, 'Washington Hospital', 'Government', 'United States', 'California', 'Medicine');
INSERT INTO COMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_STANDING, COMPANY_COUNTRY, COMPANY_STATE, COMPANY_FIELD)
        VALUES(14, 'Fixerupper Hospital', 'Private', 'United States', 'New York', 'Medicine');
INSERT INTO COMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_STANDING, COMPANY_COUNTRY, COMPANY_STATE, COMPANY_FIELD)
        VALUES(15, 'Mayo Clinic', 'Private', 'United States', 'Washington DC', 'Medicine');
INSERT INTO COMPANY(COMPANY_ID, COMPANY_NAME, COMPANY_STANDING, COMPANY_COUNTRY, COMPANY_STATE, COMPANY_FIELD)
        VALUES(16, 'Sunshine Hospital', 'Government', 'United States', 'Hawaii', 'Medicine');