--TECHNOLOGY---------------------------------------------------------------

--SOFTWARE ENGINEER TECH LEADS
--At apple
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(1, 1, 10, 2, 500000, 'Yes', 'United States', 'California');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(1, 1, 5, 5, 350000, 'Yes', 'United States', 'Washington State');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(1, 1, 12, 4, 530000, 'No', 'United States', 'California');
--At Amazon
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(2, 1, 7, 2, 400000, 'No', 'United States', 'Washington State');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(2, 1, 5, 3, 300000, 'No', 'United States', 'Florida');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(2, 1, 7, 7, 450000, 'No', 'United States', 'California');

--At Meta
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(3, 1, 12, 3, 500000, 'United States', 'California');

--SOFTWARE ENGINEERS SENIOR
--At apple
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(1, 2, 12, 5, 300000, 'United States', 'California');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(1, 2, 12, 6, 350000, 'United States', 'New York');
--At Amazon
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(2, 2, 12, 12, 400000, 'United States', 'California');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(2, 2, 3, 2, 250000, 'United States', 'California');
--At Meta
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(3, 2, 4, 4, 200000, 'United States', 'California');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(3, 2, 6, 3, 400000, 'United States', 'California');
--At Netflix
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(4, 2, 7, 5, 200000, 'United States', 'New York');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(4, 2, 15, 2, 300000, 'United States', 'California');
--At Google
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(5, 2, 10, 2, 200000, 'United States', 'California');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(5, 2, 7, 5, 275000, 'United States', 'New York');
--At IBM
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(6, 2, 8, 3, 120000, 'United States', 'Atlanta');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(6, 2, 9, 2, 118000, 'United States', 'Atlanta');

--SOFTWARE ENGINEERS JUNIOR
--At apple
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(1, 4, 12, 5, 200000, 'United States', 'California');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(1, 4, 12, 6, 250000, 'United States', 'New York');
--At Amazon
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(2, 4, 12, 12, 300000, 'United States', 'California');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(2, 4, 3, 2, 150000, 'United States', 'California');
--At Meta
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(3, 4, 4, 4, 100000, 'United States', 'California');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(3, 4, 6, 3, 300000, 'United States', 'California');
--At Netflix
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(4, 4, 7, 5, 100000, 'United States', 'New York');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(4, 4, 15, 2, 200000, 'United States', 'California');
--At Google
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(5, 4, 10, 2, 100000, 'United States', 'California');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(5, 4, 7, 5, 175000, 'United States', 'New York');
--At IBM
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(6, 4, 8, 3, 90000, 'United States', 'Atlanta');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(6, 4, 9, 2, 88000, 'United States', 'Atlanta');

--SOFTWARE ENGINEERS STAFF
--At apple
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(1, 3, 12, 5, 250000, 'United States', 'California');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(1, 3, 12, 6, 250000, 'United States', 'New York');
--At Amazon
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(2, 3, 12, 12, 350000, 'United States', 'California');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(2, 3, 3, 2, 200000, 'United States', 'California');
--At Meta
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(3, 3, 4, 4, 150000, 'United States', 'California');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(3, 3, 6, 3, 350000, 'United States', 'California');
--At Netflix
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(4, 3, 7, 5, 150000, 'United States', 'New York');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(4, 3, 15, 2, 250000, 'United States', 'California');
--At Google
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(5, 3, 10, 2, 150000, 'United States', 'California');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(5, 3, 7, 5, 225000, 'United States', 'New York');
--At IBM
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(6, 3, 8, 3, 100000, 'United States', 'Atlanta');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(6, 3, 9, 2, 108000, 'United States', 'Atlanta');

--PRODUCT MANAGERS
--At apple
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(1, 5, 10, 2, 600000, 'Yes', 'United States', 'California');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(1, 5, 5, 5, 550000, 'Yes', 'United States', 'Washington State');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(1, 5, 12, 4, 630000, 'No', 'United States', 'California');
--At Amazon
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(2, 5, 7, 2, 500000, 'No', 'United States', 'Washington State');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(2, 5, 5, 3, 450000, 'No', 'United States', 'Florida');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(2, 5, 7, 7, 450000, 'No', 'United States', 'California');

--At Meta
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(3, 5, 12, 3, 550000, 'United States', 'California');

--SYSTEMS ARCHITECTS
--At apple
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(1, 6, 10, 2, 450000, 'Yes', 'United States', 'California');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(1, 6, 5, 5, 370000, 'Yes', 'United States', 'Washington State');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(1, 6, 12, 4, 430000, 'No', 'United States', 'California');
--At Amazon
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(2, 6, 7, 2, 250000, 'No', 'United States', 'Washington State');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(2, 6, 5, 3, 200000, 'No', 'United States', 'Florida');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(2, 6, 7, 7, 450000, 'No', 'United States', 'California');

--At Meta
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(3, 6, 12, 3, 475000, 'United States', 'California');

--QUALITY ENGINEERS
--At apple
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(1, 7, 10, 2, 300000, 'Yes', 'United States', 'California');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(1, 7, 5, 5, 250000, 'Yes', 'United States', 'Washington State');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(1, 7, 12, 4, 230000, 'No', 'United States', 'California');
--At Amazon
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(2, 7, 7, 2, 200000, 'No', 'United States', 'Washington State');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(2, 7, 5, 3, 230000, 'No', 'United States', 'Florida');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE) 
        VALUES(2, 7, 7, 7, 150000, 'No', 'United States', 'California');

--At Meta
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(3, 8, 12, 3, 200000, 'United States', 'California');

--CEOs
--At apple
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
        VALUES(1, 8, 10, 2, 3200000, 'United States', 'California');
--At Amazon
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
        VALUES(2, 8, 7, 2, 4000000, 'United States', 'Washington State');

--At Meta
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(3, 8, 12, 3, 4350000, 'United States', 'California');

--At Netflix
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(4, 8, 12, 12, 3350000, 'United States', 'California');

--At Google
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(5, 8, 11, 11, 5350000, 'United States', 'California');

--At Atlanta
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE) 
    VALUES(6, 8, 30, 30, 1350000, 'United States', 'Atlanta');