--  HOSPITALITY-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- WAITER PART TIME
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(16, 2, 2, 11000, 'Canada', 'Alberta', 'ABC Pizzas', 'Canada', 'Alberta');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(16, 2, 2, 13000, 'Canada', 'Alberta', 'ABC Pizzas', 'Canada', 'Alberta');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(16, 1,  1, 13000, 'Canada', 'British Columbia', 'Best Burgers', 'Canada', 'British Columbia');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(16, 1, 1, 14000, 'United States', 'Florida', 'Wicked Waffles', 'United States', 'Florida');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(16, 2, 2, 10000, 'United States', 'Alabama', 'Sizzling Steak', 'United States', 'Alabama');
-- WAITER FULL TIME
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(17, 5, 3, 22000, 'Canada', 'Alberta', 'ABC Pizzas', 'Canada', 'Alberta');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(17, 7,4, 26000, 'Canada', 'Alberta', 'ABC Pizzas', 'Canada', 'Alberta');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(17, 1,  1, 26000, 'Canada', 'British Columbia', 'Best Burgers', 'Canada', 'British Columbia');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(17, 2, 1, 28000, 'United States', 'Florida', 'Wicked Waffles', 'United States', 'Florida');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(17, 10, 10, 20000, 'United States', 'Alabama', 'Sizzling Steak', 'United States', 'Alabama');
-- CHEF PART TIME
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(18, 2, 2, 22000, 'Canada', 'Alberta', 'ABC Pizzas', 'Canada', 'Alberta');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(18, 2, 2, 26000, 'Canada', 'Alberta', 'ABC Pizzas', 'Canada', 'Alberta');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(18, 1,  1, 32000, 'Canada', 'British Columbia', 'Best Burgers', 'Canada', 'British Columbia');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(18, 1, 1, 30000, 'United States', 'Florida', 'Wicked Waffles', 'United States', 'Florida');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(18, 2, 2, 20000, 'United States', 'Alabama', 'Sizzling Steak', 'United States', 'Alabama');
-- CHEF FULL TIME
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(19, 5, 3, 34000, 'Canada', 'Alberta', 'ABC Pizzas', 'Canada', 'Alberta');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(19, 7,4, 36000, 'Canada', 'Alberta', 'ABC Pizzas', 'Canada', 'Alberta');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(19, 1,  1, 37000, 'Canada', 'British Columbia', 'Best Burgers', 'Canada', 'British Columbia');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(19, 2, 1, 42000, 'United States', 'Florida', 'Wicked Waffles', 'United States', 'Florida');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(19, 10, 10, 35000, 'United States', 'Alabama', 'Sizzling Steak', 'United States', 'Alabama');
-- MANAGER PART TIME
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(20, 2, 2, 32000, 'Canada', 'Alberta', 'ABC Pizzas', 'Canada', 'Alberta');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(20, 2, 2, 29000, 'Canada', 'Alberta', 'ABC Pizzas', 'Canada', 'Alberta');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(20, 1,  1, 29000, 'Canada', 'British Columbia', 'Best Burgers', 'Canada', 'British Columbia');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(20, 1, 1, 30000, 'United States', 'Florida', 'Wicked Waffles', 'United States', 'Florida');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(20, 2, 2, 20000, 'United States', 'Alabama', 'Sizzling Steak', 'United States', 'Alabama');
-- MANAGER FULL TIME
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(21, 5, 3, 45000, 'Canada', 'Alberta', 'ABC Pizzas', 'Canada', 'Alberta');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(21, 7,4, 42000, 'Canada', 'Alberta', 'ABC Pizzas', 'Canada', 'Alberta');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(21, 1,  1, 47000, 'Canada', 'British Columbia', 'Best Burgers', 'Canada', 'British Columbia');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(21, 2, 1, 48500, 'United States', 'Florida', 'Wicked Waffles', 'United States', 'Florida');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(21, 10, 10, 36000, 'United States', 'Alabama', 'Sizzling Steak', 'United States', 'Alabama');

-- OWNER
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(22, 5, 3, 75000, 'Canada', 'Alberta', 'ABC Pizzas', 'Canada', 'Alberta');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(22, 1,  1, 66000, 'Canada', 'British Columbia', 'Best Burgers', 'Canada', 'British Columbia');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(22, 2, 1, 68000, 'United States', 'Florida', 'Wicked Waffles', 'United States', 'Florida');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(22, 10, 10, 52000, 'United States', 'Alabama', 'Sizzling Steak', 'United States', 'Alabama');