-- BUSINESS---------------------------------------------------------------------------

-- HUMAN RESOURCE
-- Apple HR w/ two diff locations
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
        VALUES(23, 10, 5, 80000, 'Yes', 'United States', 'California', 'Apple', 'United States', 'California');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
        VALUES(23, 8, 3, 85000, 'No', 'United States', 'California', 'Apple', 'United States', 'California');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
        VALUES(23, 7, 2, 70000, 'Yes', 'United States', 'New York', 'Apple', 'United States', 'California');
-- Amazon HR
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
        VALUES(23, 5, 4, 72000, 'Yes', 'United States', 'New York', 'Amazon', 'United States', 'Washington State');
-- Meta HR from 2 diff locations
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
        VALUES(23, 1, 1, 88000, 'No', 'United States', 'California', 'Meta', 'United States', 'California');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
        VALUES(23, 2, 1, 45000, 'Yes', 'United States', 'Alabama', 'Meta', 'United States', 'California');
-- Medical Hospital HR @ NY or CA
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
        VALUES(23, 3, 1, 60000, 'Yes', 'United States', 'New York', 'Washington Hospital', 'United States', 'California');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
        VALUES(23, 4, 2, 62000, 'No', 'United States', 'New York', 'Fixerupper Hospital', 'United States', 'New York');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
        VALUES(23, 7, 5, 66000, 'Yes', 'United States', 'California', 'Mayo Clinic', 'United States', 'Washington DC');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
        VALUES(23, 12, 6, 65000, 'No', 'United States', 'California', 'Sunshine Hospital', 'United States', 'Hawaii');