-- BUSINESS---------------------------------------------------------------------------

-- HUMAN RESOURCE
-- Apple HR w/ two diff locations
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
        VALUES(1, 23, 10, 5, 80000, 'Yes', 'United States', 'California', 'Apple', 'Human Resource');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
        VALUES(1, 23, 8, 3, 85000, 'No', 'United States', 'California', 'Apple', 'Human Resource');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
        VALUES(1, 23, 7, 2, 70000, 'Yes', 'United States', 'New York', 'Apple', 'Human Resource');
-- Amazon HR
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
        VALUES(2, 23, 5, 4, 72000, 'Yes', 'United States', 'New York', 'Amazon', 'Human Resource');
-- Meta HR from 2 diff locations
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
        VALUES(3, 23, 1, 1, 88000, 'No', 'United States', 'California', 'Meta', 'Human Resource');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
        VALUES(3, 23, 2, 1, 45000, 'Yes', 'United States', 'Alabama', 'Meta', 'Human Resource');
-- Medical Hospital HR @ NY or CA
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
        VALUES(13, 23, 3, 1, 60000, 'Yes', 'United States', 'New York', 'Washington Hospital', 'Human Resource');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
        VALUES(14, 23, 4, 2, 62000, 'No', 'United States', 'New York', 'Fixerupper Hospital', 'Human Resource');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
        VALUES(15, 23, 7, 5, 66000, 'Yes', 'United States', 'California', 'Mayo Clinic', 'Human Resource');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, NEGOTIATED, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
        VALUES(16, 23, 12, 6, 65000, 'No', 'United States', 'California', 'Sunshine Hospital', 'Human Resource');