-- Populating location table
INSERT INTO LOCATION(COUNTRY, STATE) VALUES ('United States', 'California');
INSERT INTO LOCATION(COUNTRY, STATE) VALUES ('United States', 'Georgia');
INSERT INTO LOCATION(COUNTRY, STATE) VALUES ('United States', 'Alaska');
INSERT INTO LOCATION(COUNTRY, STATE) VALUES ('United States', 'New York');
INSERT INTO LOCATION(COUNTRY, STATE) VALUES ('United States', 'Washington State');
INSERT INTO LOCATION(COUNTRY, STATE) VALUES ('United States', 'Washington DC');
INSERT INTO LOCATION(COUNTRY, STATE) VALUES ('United States', 'Florida');
INSERT INTO LOCATION(COUNTRY, STATE) VALUES ('United States', 'Hawaii');
INSERT INTO LOCATION(COUNTRY, STATE) VALUES ('United States', 'Alabama');
INSERT INTO LOCATION(COUNTRY, STATE) VALUES ('Canada', 'Alberta');
INSERT INTO LOCATION(COUNTRY, STATE) VALUES ('Canada', 'Manitoba');
INSERT INTO LOCATION(COUNTRY, STATE) VALUES ('Canada', 'British Columbia');
INSERT INTO LOCATION(COUNTRY, STATE) VALUES ('Canada', 'Ontario');
INSERT INTO LOCATION(COUNTRY, STATE) VALUES ('Canada', 'Quebec');