-- Populating field table
INSERT INTO FIELD(NAME) VALUES ('Technology');
INSERT INTO FIELD(NAME) VALUES ('Medicine');
INSERT INTO FIELD(NAME) VALUES ('Hospitality');
INSERT INTO FIELD(NAME) VALUES ('Engineering');
INSERT INTO FIELD(NAME) VALUES('Construction');
INSERT INTO FIELD(NAME) VALUES('Military');
INSERT INTO FIELD(NAME) VALUES('Education');
INSERT INTO FIELD(NAME) VALUES('Business');