--  HOSPITALITY-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- WAITER PART TIME
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(7, 16, 2, 2, 11000, 'Canada', 'Alberta', 'ABC Pizzas', 'Waiter');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(7, 16, 2, 2, 13000, 'Canada', 'Alberta', 'ABC Pizzas', 'Waiter');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(8, 16, 1,  1, 13000, 'Canada', 'British Columbia', 'Best Burgers', 'Waiter');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(9, 16, 1, 1, 14000, 'United States', 'Florida', 'Wicked Waffles', 'Waiter');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(10, 16, 2, 2, 10000, 'United States', 'Alabama', 'Sizzling Steak', 'Waiter');
-- WAITER FULL TIME
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(7, 17, 5, 3, 22000, 'Canada', 'Alberta', 'ABC Pizzas', 'Waiter');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(7, 17, 7,4, 26000, 'Canada', 'Alberta', 'ABC Pizzas', 'Waiter');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(8, 17, 1,  1, 26000, 'Canada', 'British Columbia', 'Best Burgers', 'Waiter');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(9, 17, 2, 1, 28000, 'United States', 'Florida', 'Wicked Waffles', 'Waiter');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(10, 17, 10, 10, 20000, 'United States', 'Alabama', 'Sizzling Steak', 'Waiter');
-- CHEF PART TIME
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(7, 18, 2, 2, 22000, 'Canada', 'Alberta', 'ABC Pizzas', 'Chef');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(7, 18, 2, 2, 26000, 'Canada', 'Alberta', 'ABC Pizzas', 'Chef');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(8, 18, 1,  1, 32000, 'Canada', 'British Columbia', 'Best Burgers', 'Chef');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(9, 18, 1, 1, 30000, 'United States', 'Florida', 'Wicked Waffles', 'Chef');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(10, 18, 2, 2, 20000, 'United States', 'Alabama', 'Sizzling Steak', 'Chef');
-- CHEF FULL TIME
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(7, 19, 5, 3, 34000, 'Canada', 'Alberta', 'ABC Pizzas', 'Chef');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(7, 19, 7,4, 36000, 'Canada', 'Alberta', 'ABC Pizzas', 'Chef');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(8, 19, 1,  1, 37000, 'Canada', 'British Columbia', 'Best Burgers', 'Chef');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(9, 19, 2, 1, 42000, 'United States', 'Florida', 'Wicked Waffles', 'Chef');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(10, 19, 10, 10, 35000, 'United States', 'Alabama', 'Sizzling Steak', 'Chef');
-- MANAGER PART TIME
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(7, 20, 2, 2, 32000, 'Canada', 'Alberta', 'ABC Pizzas', 'Manager');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(7, 20, 2, 2, 29000, 'Canada', 'Alberta', 'ABC Pizzas', 'Manager');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(8, 20, 1,  1, 29000, 'Canada', 'British Columbia', 'Best Burgers', 'Manager');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(9, 20, 1, 1, 30000, 'United States', 'Florida', 'Wicked Waffles', 'Manager');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(10, 20, 2, 2, 20000, 'United States', 'Alabama', 'Sizzling Steak', 'Manager');
-- MANAGER FULL TIME
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(7, 21, 5, 3, 45000, 'Canada', 'Alberta', 'ABC Pizzas', 'Manager');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(7, 21, 7,4, 42000, 'Canada', 'Alberta', 'ABC Pizzas', 'Manager');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(8, 21, 1,  1, 47000, 'Canada', 'British Columbia', 'Best Burgers', 'Manager');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(9, 21, 2, 1, 48500, 'United States', 'Florida', 'Wicked Waffles', 'Manager');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(10, 21, 10, 10, 36000, 'United States', 'Alabama', 'Sizzling Steak', 'Manager');

-- OWNER
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(7, 22, 5, 3, 75000, 'Canada', 'Alberta', 'ABC Pizzas', 'Owner');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(8, 22, 1,  1, 66000, 'Canada', 'British Columbia', 'Best Burgers', 'Owner');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(9, 22, 2, 1, 68000, 'United States', 'Florida', 'Wicked Waffles', 'Owner');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(10, 22, 10, 10, 52000, 'United States', 'Alabama', 'Sizzling Steak', 'Owner');