-- MEDICINE-- -- -- -- -- -- 

-- FAMILY PHYSICIANS
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(13, 9, 12, 12, 435000, 'United States', 'California', 'Washington Hospital', 'Family Physician');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(14, 9, 25,  25, 535000, 'United States', 'New York', 'Fixerupper Hospital', 'Family Physician');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(15, 9, 30, 30, 235000, 'United States', 'Washington DC', 'Mayo Clinic', 'Family Physician');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(16, 9, 28, 28, 335000, 'United States', 'Hawaii', 'Sunshine Hospital', 'Family Physician');

-- SENIOR FULL TIME DAY NURSES
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(13, 12, 12, 12, 65000, 'United States', 'California', 'Washington Hospital', 'Nurse');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(14, 12, 25,  25, 73000, 'United States', 'New York', 'Fixerupper Hospital', 'Nurse');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(15, 12, 30, 30, 53000, 'United States', 'Washington DC', 'Mayo Clinic', 'Nurse');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(16, 12, 28, 28, 45000, 'United States', 'Hawaii', 'Sunshine Hospital', 'Nurse');

-- SENIOR FULL TIME NIGHT NURSES
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(13, 10, 12, 12, 75000, 'United States', 'California', 'Washington Hospital', 'Nurse');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(14, 10, 25,  25, 78000, 'United States', 'New York', 'Fixerupper Hospital', 'Nurse');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(15, 10, 30, 30, 58000, 'United States', 'Washington DC', 'Mayo Clinic', 'Nurse');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(16, 10, 28, 28, 50000, 'United States', 'Hawaii', 'Sunshine Hospital', 'Nurse');

-- JUNIOR PART TIME DAY NURSES
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(13, 13, 12, 12, 45000, 'United States', 'California', 'Washington Hospital', 'Nurse');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(14, 13, 25,  25, 43000, 'United States', 'New York', 'Fixerupper Hospital', 'Nurse');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(15, 13, 30, 30, 30000, 'United States', 'Washington DC', 'Mayo Clinic', 'Nurse');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(16, 13, 28, 28, 28000, 'United States', 'Hawaii', 'Sunshine Hospital', 'Nurse');

-- JUNIOR PART TIME NIGHT NURSES
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(13, 11, 12, 12, 50000, 'United States', 'California', 'Washington Hospital', 'Nurse');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(14, 11, 25,  25, 48000, 'United States', 'New York', 'Fixerupper Hospital', 'Nurse');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(15, 11, 30, 30, 35000, 'United States', 'Washington DC', 'Mayo Clinic', 'Nurse');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(16, 11, 28, 28, 33000, 'United States', 'Hawaii', 'Sunshine Hospital', 'Nurse');

-- ADMINISTRATORS DAY
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(13, 14, 12, 12, 70000, 'United States', 'California', 'Washington Hospital', 'Administrator');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(14, 14, 25,  25, 72000, 'United States', 'New York', 'Fixerupper Hospital', 'Administrator');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(15, 14, 30, 30, 65000, 'United States', 'Washington DC', 'Mayo Clinic', 'Administrator');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(16, 14, 28, 28, 58000, 'United States', 'Hawaii', 'Sunshine Hospital', 'Administrator');

-- ADMINISTRATORS NIGHT
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(13, 15, 12, 12, 78000, 'United States', 'California', 'Washington Hospital', 'Administrator');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(14, 15, 25,  25, 82000, 'United States', 'New York', 'Fixerupper Hospital', 'Administrator');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(15, 15, 30, 30, 72000, 'United States', 'Washington DC', 'Mayo Clinic', 'Administrator');
INSERT INTO USER_INPUT(USER_COMPANY_ID, USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_JOB_NAME) 
    VALUES(16, 15, 28, 28, 64000, 'United States', 'Hawaii', 'Sunshine Hospital', 'Administrator');