-- Inserting into COMPANY NAME Table
INSERT INTO COMPANYNAME(NAME) VALUES ('Apple');
INSERT INTO COMPANYNAME(NAME) VALUES ('Amazon');
INSERT INTO COMPANYNAME(NAME) VALUES ('Meta');
INSERT INTO COMPANYNAME(NAME) VALUES ('Netflix');
INSERT INTO COMPANYNAME(NAME) VALUES ('Google');
INSERT INTO COMPANYNAME(NAME) VALUES ('IBM');
INSERT INTO COMPANYNAME(NAME) VALUES ('ABC Pizzas');
INSERT INTO COMPANYNAME(NAME) VALUES ('Best Burgers');
INSERT INTO COMPANYNAME(NAME) VALUES ('Wicked Waffles');
INSERT INTO COMPANYNAME(NAME) VALUES ('Sizzling Steak');
INSERT INTO COMPANYNAME(NAME) VALUES ('Nice Nachos');
INSERT INTO COMPANYNAME(NAME) VALUES ('Krispy Krabs');
INSERT INTO COMPANYNAME(NAME) VALUES ('Washington Hospital');
INSERT INTO COMPANYNAME(NAME) VALUES ('Fixerupper Hospital');
INSERT INTO COMPANYNAME(NAME) VALUES ('Mayo Clinic');
INSERT INTO COMPANYNAME(NAME) VALUES ('Sunshine Hospital');