-- MEDICINE-------------------------------------------------------------------

-- FAMILY PHYSICIANS
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(9, 12, 12, 435000, 'United States', 'California', 'Washington Hospital', 'United States', 'California');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(9, 25,  25, 535000, 'United States', 'New York', 'Fixerupper Hospital', 'United States', 'New York');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(9, 30, 30, 235000, 'United States', 'Washington DC', 'Mayo Clinic', 'United States', 'Washington DC');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(9, 28, 28, 335000, 'United States', 'Hawaii', 'Sunshine Hospital', 'United States', 'Hawaii');

-- SENIOR FULL TIME DAY NURSES
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(12, 12, 12, 65000, 'United States', 'California', 'Washington Hospital', 'United States', 'California');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(12, 25,  25, 73000, 'United States', 'New York', 'Fixerupper Hospital', 'United States', 'New York');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(12, 30, 30, 53000, 'United States', 'Washington DC', 'Mayo Clinic', 'United States', 'Washington DC');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(12, 28, 28, 45000, 'United States', 'Hawaii', 'Sunshine Hospital', 'United States', 'Hawaii');

-- SENIOR FULL TIME NIGHT NURSES
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(10, 12, 12, 75000, 'United States', 'California', 'Washington Hospital', 'United States', 'California');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(10, 25,  25, 78000, 'United States', 'New York', 'Fixerupper Hospital', 'United States', 'New York');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(10, 30, 30, 58000, 'United States', 'Washington DC', 'Mayo Clinic', 'United States', 'Washington DC');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(10, 28, 28, 50000, 'United States', 'Hawaii', 'Sunshine Hospital', 'United States', 'Hawaii');

-- JUNIOR PART TIME DAY NURSES
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(13, 12, 12, 45000, 'United States', 'California', 'Washington Hospital', 'United States', 'California');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(13, 25,  25, 43000, 'United States', 'New York', 'Fixerupper Hospital', 'United States', 'New York');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(13, 30, 30, 30000, 'United States', 'Washington DC', 'Mayo Clinic', 'United States', 'Washington DC');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(13, 28, 28, 28000, 'United States', 'Hawaii', 'Sunshine Hospital', 'United States', 'Hawaii');

-- JUNIOR PART TIME NIGHT NURSES
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(11, 12, 12, 50000, 'United States', 'California', 'Washington Hospital', 'United States', 'California');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(11, 25,  25, 48000, 'United States', 'New York', 'Fixerupper Hospital', 'United States', 'New York');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(11, 30, 30, 35000, 'United States', 'Washington DC', 'Mayo Clinic', 'United States', 'Washington DC');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(11, 28, 28, 33000, 'United States', 'Hawaii', 'Sunshine Hospital', 'United States', 'Hawaii');

-- ADMINISTRATORS DAY
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(14, 12, 12, 70000, 'United States', 'California', 'Washington Hospital', 'United States', 'California');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(14, 25,  25, 72000, 'United States', 'New York', 'Fixerupper Hospital', 'United States', 'New York');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(14, 30, 30, 65000, 'United States', 'Washington DC', 'Mayo Clinic', 'United States', 'Washington DC');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(14, 28, 28, 58000, 'United States', 'Hawaii', 'Sunshine Hospital', 'United States', 'Hawaii');

-- ADMINISTRATORS NIGHT
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(15, 12, 12, 78000, 'United States', 'California', 'Washington Hospital', 'United States', 'California');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(15, 25,  25, 82000, 'United States', 'New York', 'Fixerupper Hospital', 'United States', 'New York');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(15, 30, 30, 72000, 'United States', 'Washington DC', 'Mayo Clinic', 'United States', 'Washington DC');
INSERT INTO USER_INPUT(USER_JOB_ID, YEARS_WORKING, YEARS_AT_COMPANY, SALARY, USER_COUNTRY, USER_STATE, USER_COMPANY_NAME, USER_COMPANY_COUNTRY, USER_COMPANY_STATE) 
    VALUES(15, 28, 28, 64000, 'United States', 'Hawaii', 'Sunshine Hospital', 'United States', 'Hawaii');
