-- Get all user inputs w/ Input Id, Company name, Job name, state and salary

SELECT USER_ENTRY.ENTRY_ID, COMPANY.COMPANY_NAME, COMPANY.COMPANY_COUNTRY, JOB.JOB_NAME, 
    USER_INPUT.USER_STATE, USER_INPUT.SALARY
FROM ((USER_ENTRY 
	LEFT JOIN USER_INPUT 
		ON USER_ENTRY.USER_INPUT_ID = USER_INPUT.INPUT_ID)
	LEFT JOIN COMPANY 
		ON USER_INPUT.USER_COMPANY_NAME = COMPANY.COMPANY_NAME
		AND USER_INPUT.USER_COMPANY_COUNTRY = COMPANY.COMPANY_COUNTRY
		AND USER_INPUT.USER_COMPANY_STATE = COMPANY.COMPANY_STATE)
LEFT JOIN JOB 
	ON USER_INPUT.USER_JOB_ID = JOB.JOB_ID;

-- Get all user inputs and display all job information 
-- (as much detail about the job as possible)
SELECT USER_ENTRY.ENTRY_ID, 
	COMPANY.COMPANY_NAME, 
	JOB.JOB_NAME, JOB.JOB_LEVEL, JOB.JOB_COMMITMENT, JOB.JOB_SHIFT_TIME, JOB.JOB_LOCATION_TYPE, JOB.JOB_FIELD,
	USER_INPUT.USER_STATE, USER_INPUT.USER_COUNTRY, USER_INPUT.SALARY
FROM ((USER_ENTRY 
	LEFT JOIN USER_INPUT 
		ON USER_ENTRY.USER_INPUT_ID = USER_INPUT.INPUT_ID) 
	LEFT JOIN COMPANY 
		ON USER_INPUT.USER_COMPANY_NAME = COMPANY.COMPANY_NAME
		AND USER_INPUT.USER_COMPANY_COUNTRY = COMPANY.COMPANY_COUNTRY
		AND USER_INPUT.USER_COMPANY_STATE = COMPANY.COMPANY_STATE)
	LEFT JOIN JOB ON USER_INPUT.USER_JOB_ID = JOB.JOB_ID;

-- Get all user inputs with criteria "night shift" 
SELECT USER_ENTRY.ENTRY_ID, COMPANY.COMPANY_NAME, JOB.JOB_NAME, 
    USER_INPUT.USER_STATE, USER_INPUT.SALARY, JOB.JOB_SHIFT_TIME
FROM ((USER_ENTRY 
	LEFT JOIN USER_INPUT 
		ON USER_ENTRY.USER_INPUT_ID = USER_INPUT.INPUT_ID) 
	LEFT JOIN COMPANY 
		ON USER_INPUT.USER_COMPANY_NAME = COMPANY.COMPANY_NAME
		AND USER_INPUT.USER_COMPANY_COUNTRY = COMPANY.COMPANY_COUNTRY
		AND USER_INPUT.USER_COMPANY_STATE = COMPANY.COMPANY_STATE)
	LEFT JOIN JOB 
		ON USER_INPUT.USER_JOB_ID = JOB.JOB_ID
WHERE JOB.JOB_SHIFT_TIME = 'Night';

-- Get all user inputs with criteria Tech field & in California
SELECT USER_INPUT.INPUT_ID, COMPANY.COMPANY_NAME, JOB.JOB_NAME, 
    USER_INPUT.USER_STATE, USER_INPUT.SALARY, JOB.JOB_FIELD
FROM ((USER_ENTRY 
	LEFT JOIN USER_INPUT 
		ON USER_ENTRY.USER_INPUT_ID = USER_INPUT.INPUT_ID) 
	LEFT JOIN COMPANY 
		ON USER_INPUT.USER_COMPANY_NAME = COMPANY.COMPANY_NAME
		AND USER_INPUT.USER_COMPANY_COUNTRY = COMPANY.COMPANY_COUNTRY
		AND USER_INPUT.USER_COMPANY_STATE = COMPANY.COMPANY_STATE)
	LEFT JOIN JOB 
		ON USER_INPUT.USER_JOB_ID = JOB.JOB_ID
WHERE JOB.JOB_FIELD = 'Technology'
    AND USER_INPUT.USER_STATE = 'California';

-- Get all user inputs with criteria junior software developer
SELECT USER_INPUT.INPUT_ID, COMPANY.COMPANY_NAME, JOB.JOB_NAME, 
    JOB.JOB_LEVEL, USER_INPUT.USER_STATE, USER_INPUT.SALARY
FROM ((USER_ENTRY 
	LEFT JOIN USER_INPUT 
		ON USER_ENTRY.USER_INPUT_ID = USER_INPUT.INPUT_ID)
	LEFT JOIN COMPANY 
		ON USER_INPUT.USER_COMPANY_NAME = COMPANY.COMPANY_NAME
		AND USER_INPUT.USER_COMPANY_COUNTRY = COMPANY.COMPANY_COUNTRY
		AND USER_INPUT.USER_COMPANY_STATE = COMPANY.COMPANY_STATE)
	LEFT JOIN JOB 
		ON USER_INPUT.USER_JOB_ID = JOB.JOB_ID
WHERE JOB.JOB_NAME = 'Software Developer'
    AND JOB.JOB_LEVEL = 'Junior';
   
-- Get all user inputs with salary > 500 k
-- We also want to see what fields these jobs belong to
SELECT USER_INPUT.INPUT_ID, COMPANY.COMPANY_NAME, JOB.JOB_NAME, 
    JOB.JOB_LEVEL, JOB.JOB_FIELD, USER_INPUT.USER_STATE, USER_INPUT.SALARY
FROM ((USER_ENTRY 
	LEFT JOIN USER_INPUT 
		ON USER_ENTRY.USER_INPUT_ID = USER_INPUT.INPUT_ID)
	LEFT JOIN COMPANY 
		ON USER_INPUT.USER_COMPANY_NAME = COMPANY.COMPANY_NAME
		AND USER_INPUT.USER_COMPANY_COUNTRY = COMPANY.COMPANY_COUNTRY
		AND USER_INPUT.USER_COMPANY_STATE = COMPANY.COMPANY_STATE)
	LEFT JOIN JOB 
		ON USER_INPUT.USER_JOB_ID = JOB.JOB_ID
WHERE USER_INPUT.SALARY >= 500000;

-- Get all user inputs with all inputs from Canada
SELECT USER_INPUT.INPUT_ID, COMPANY.COMPANY_NAME, JOB.JOB_NAME, 
    USER_INPUT.USER_STATE, USER_INPUT.USER_COUNTRY,
    USER_INPUT.SALARY
FROM ((USER_ENTRY 
	LEFT JOIN USER_INPUT 
		ON USER_ENTRY.USER_INPUT_ID = USER_INPUT.INPUT_ID)
	LEFT JOIN COMPANY 
		ON USER_INPUT.USER_COMPANY_NAME = COMPANY.COMPANY_NAME
		AND USER_INPUT.USER_COMPANY_COUNTRY = COMPANY.COMPANY_COUNTRY
		AND USER_INPUT.USER_COMPANY_STATE = COMPANY.COMPANY_STATE)
	LEFT JOIN JOB 
		ON USER_INPUT.USER_JOB_ID = JOB.JOB_ID
WHERE USER_INPUT.USER_COUNTRY = 'Canada';

-- Get all user inputs from Apple
SELECT USER_INPUT.INPUT_ID, COMPANY.COMPANY_NAME, JOB.JOB_NAME, 
    USER_INPUT.USER_STATE, USER_INPUT.SALARY
FROM ((USER_ENTRY 
	LEFT JOIN USER_INPUT 
		ON USER_ENTRY.USER_INPUT_ID = USER_INPUT.INPUT_ID)
	LEFT JOIN COMPANY 
		ON USER_INPUT.USER_COMPANY_NAME = COMPANY.COMPANY_NAME
		AND USER_INPUT.USER_COMPANY_COUNTRY = COMPANY.COMPANY_COUNTRY
		AND USER_INPUT.USER_COMPANY_STATE = COMPANY.COMPANY_STATE)
	LEFT JOIN JOB 
		ON USER_INPUT.USER_JOB_ID = JOB.JOB_ID
    WHERE COMPANY.COMPANY_NAME = 'Apple';

-- Get all part time job information
SELECT USER_INPUT.INPUT_ID, COMPANY.COMPANY_NAME, JOB.JOB_NAME, 
    USER_INPUT.USER_STATE, USER_INPUT.USER_COUNTRY,
    JOB.JOB_COMMITMENT, USER_INPUT.SALARY
FROM ((USER_ENTRY 
	LEFT JOIN USER_INPUT 
		ON USER_ENTRY.USER_INPUT_ID = USER_INPUT.INPUT_ID)
	LEFT JOIN COMPANY 
		ON USER_INPUT.USER_COMPANY_NAME = COMPANY.COMPANY_NAME
		AND USER_INPUT.USER_COMPANY_COUNTRY = COMPANY.COMPANY_COUNTRY
		AND USER_INPUT.USER_COMPANY_STATE = COMPANY.COMPANY_STATE)
	LEFT JOIN JOB 
		ON USER_INPUT.USER_JOB_ID = JOB.JOB_ID
WHERE JOB.JOB_COMMITMENT = 'Part-time';

-- All HR entries (allows us to explore in depth salary variation which may 
-- stem from location, company or other factors)
SELECT USER_INPUT.INPUT_ID, COMPANY.COMPANY_NAME, JOB.JOB_NAME, 
    USER_INPUT.USER_STATE, USER_INPUT.SALARY, JOB.JOB_FIELD
FROM ((USER_ENTRY 
	LEFT JOIN USER_INPUT 
		ON USER_ENTRY.USER_INPUT_ID = USER_INPUT.INPUT_ID) 
	LEFT JOIN COMPANY 
		ON USER_INPUT.USER_COMPANY_NAME = COMPANY.COMPANY_NAME
		AND USER_INPUT.USER_COMPANY_COUNTRY = COMPANY.COMPANY_COUNTRY
		AND USER_INPUT.USER_COMPANY_STATE = COMPANY.COMPANY_STATE)
	LEFT JOIN JOB 
		ON USER_INPUT.USER_JOB_ID = JOB.JOB_ID
WHERE JOB.JOB_NAME = 'Human Resource';